// TYPE CONSTANTS
export const CHANGE_PEG_COLOR = "CHANGE_PEG_COLOR";
export const ADD_GUESS = "ADD_GUESS";
export const GENERATE_CODE = "GENERATE_CODE";
export const RESET_GUESSES = "RESET_GUESSES";
